---
include:
  - local: .gitlab-ci.templates.yml

stages:
  - lint
  - build-1
  - build-2
  - build-3

default:
  interruptible: true

github-superliner/lint:
  stage: lint
  image:
    name: github/super-linter:slim-v4
    entrypoint: [ "" ]
  variables:
    RUN_LOCAL: "true"
    VALIDATE_NATURAL_LANGUAGE: "false"
    IGNORE_GITIGNORED_FILES: "true"
    DEFAULT_WORKSPACE: ${CI_PROJECT_DIR}
    ANSIBLE_DIRECTORY: ${CI_PROJECT_DIR}
    LINTER_RULES_PATH: ${CI_PROJECT_DIR}
  script:
    - /action/lib/linter.sh
  artifacts:
    untracked: true

core/build:
  stage: build-1
  extends:
    - .docker
  resource_group: core
  variables:
    DOCKER_EXTRA_ARGS: |
      core
      --file core/Dockerfile
      --build-arg PARENT_TAG=${CI_COMMIT_REF_SLUG}
      --tag ${CI_REGISTRY_IMAGE}/core:${CI_COMMIT_REF_SLUG}
      --cache-from type=registry,ref=${CI_REGISTRY_IMAGE}/core-cache:${CI_COMMIT_REF_SLUG}
      --cache-to type=registry,ref=${CI_REGISTRY_IMAGE}/core-cache:${CI_COMMIT_REF_SLUG},mode=max

nginx/build:
  stage: build-2
  extends:
    - .docker
  resource_group: nginx
  variables:
    DOCKER_EXTRA_ARGS: |
      nginx
      --file nginx/Dockerfile
      --build-arg PARENT_TAG=${CI_COMMIT_REF_SLUG}
      --tag ${CI_REGISTRY_IMAGE}/nginx:${CI_COMMIT_REF_SLUG}
      --cache-from type=registry,ref=${CI_REGISTRY_IMAGE}/nginx-cache:${CI_COMMIT_REF_SLUG}
      --cache-to type=registry,ref=${CI_REGISTRY_IMAGE}/nginx-cache:${CI_COMMIT_REF_SLUG},mode=max
  needs:
    - job: core/build

terratools/build:
  stage: build-2
  extends:
    - .docker
  resource_group: terratools
  variables:
    DOCKER_EXTRA_ARGS: |
      terratools
      --file terratools/Dockerfile
      --build-arg PARENT_TAG=${CI_COMMIT_REF_SLUG}
      --tag ${CI_REGISTRY_IMAGE}/terratools:${CI_COMMIT_REF_SLUG}
      --cache-from type=registry,ref=${CI_REGISTRY_IMAGE}/terratools-cache:${CI_COMMIT_REF_SLUG}
      --cache-to type=registry,ref=${CI_REGISTRY_IMAGE}/terratools-cache:${CI_COMMIT_REF_SLUG},mode=max
  needs:
    - job: core/build

kubetools/build:
  stage: build-2
  extends:
    - .docker
  resource_group: kubetools
  variables:
    DOCKER_EXTRA_ARGS: |
      kubetools
      --file kubetools/Dockerfile
      --build-arg PARENT_TAG=${CI_COMMIT_REF_SLUG}
      --tag ${CI_REGISTRY_IMAGE}/kubetools:${CI_COMMIT_REF_SLUG}
      --cache-from type=registry,ref=${CI_REGISTRY_IMAGE}/kubetools-cache:${CI_COMMIT_REF_SLUG}
      --cache-to type=registry,ref=${CI_REGISTRY_IMAGE}/kubetools-cache:${CI_COMMIT_REF_SLUG},mode=max
  needs:
    - job: core/build

python-3.9/build:
  stage: build-2
  extends:
    - .docker
    - .python
  variables:
    PYTHON_SELECTOR: "3_9"

python-3.10/build:
  stage: build-2
  extends:
    - .docker
    - .python
  variables:
    PYTHON_SELECTOR: "3_10"

golang-1.17-minimal/build:
  stage: build-2
  extends:
    - .docker
    - .golang_minimal
  variables:
    GOLANG_SELECTOR: "17"

golang-1.18-minimal/build:
  stage: build-2
  extends:
    - .docker
    - .golang_minimal
  variables:
    GOLANG_SELECTOR: "18"

nodejs-16-minimal/build:
  stage: build-2
  extends:
    - .docker
    - .nodejs_minimal
  variables:
    NODEJS_SELECTOR: "16"

nodejs-18-minimal/build:
  stage: build-2
  extends:
    - .docker
    - .nodejs_minimal
  variables:
    NODEJS_SELECTOR: "18"

golang-1.17-full/build:
  stage: build-3
  extends:
    - .docker
    - .golang_full
  variables:
    GOLANG_SELECTOR: "17"
  needs:
    - job: golang-1.17-minimal/build

golang-1.18-full/build:
  stage: build-3
  extends:
    - .docker
    - .golang_full
  variables:
    GOLANG_SELECTOR: "18"
  needs:
    - job: golang-1.18-minimal/build

nodejs-16-full/build:
  stage: build-3
  extends:
    - .docker
    - .nodejs_full
  variables:
    NODEJS_SELECTOR: "16"
  needs:
    - job: nodejs-16-minimal/build

nodejs-18-full/build:
  stage: build-3
  extends:
    - .docker
    - .nodejs_full
  variables:
    NODEJS_SELECTOR: "18"
  needs:
    - job: nodejs-18-minimal/build
